const provinces = [
    { plate: "01", name: "Adana", desc: "Adana, Türkiye'nin güneyinde yer alan ve tarımıyla öne çıkan önemli bir ilimizdir. Seyhan Nehri üzerine kuruludur." },
    { plate: "02", name: "Adıyaman", desc: "Adıyaman, Güneydoğu Anadolu Bölgesi'nde yer alır. Nemrut Dağı ile ünlüdür." },
    { plate: "03", name: "Afyonkarahisar", desc: "Afyonkarahisar, termal suları, mermeri ve kaymağı ile meşhurdur." },
    { plate: "04", name: "Ağrı", desc: "Ağrı, Türkiye'nin en yüksek dağı olan Ağrı Dağı'na ev sahipliği yapar." },
    { plate: "05", name: "Amasya", desc: "Amasya, Şehzadeler şehri olarak bilinir ve elmasıyla meşhurdur." },
    { plate: "06", name: "Ankara", desc: "Ankara, Türkiye Cumhuriyeti'nin başkentidir. Anıtkabir burada yer almaktadır." },
    { plate: "07", name: "Antalya", desc: "Antalya, turizmin başkentidir ve muhteşem plajlara sahiptir." },
    { plate: "08", name: "Artvin", desc: "Artvin, Karadeniz'in yeşil incisidir ve doğal güzellikleriyle büyüleyicidir." },
    { plate: "09", name: "Aydın", desc: "Aydın, Ege Bölgesi'nin önemli tarım ve turizm merkezlerinden biridir. İnciri meşhurdur." },
    { plate: "10", name: "Balıkesir", desc: "Balıkesir, hem Marmara hem de Ege Denizi'ne kıyısı olan güzel bir ilimizdir." },
    { plate: "11", name: "Bilecik", desc: "Bilecik, Osmanlı İmparatorluğu'nun temellerinin atıldığı tarihi bir şehirdir." },
    { plate: "12", name: "Bingöl", desc: "Bingöl, Doğu Anadolu'da yer alan doğal gölleriyle bilinen bir ildir." },
    { plate: "13", name: "Bitlis", desc: "Bitlis, tarihi dokusu ve yöresel mimarisi ile dikkat çeker." },
    { plate: "14", name: "Bolu", desc: "Bolu, gölleri ve ormanlarıyla Türkiye'nin doğa cennetlerinden biridir. Abant çok popülerdir." },
    { plate: "15", name: "Burdur", desc: "Burdur, Göller Yöresi'nde bulunur ve Salda Gölü ile ünlüdür." },
    { plate: "16", name: "Bursa", desc: "Bursa, Osmanlı'ya başkentlik yapmış, Uludağ'ı ve kestane şekeri ile meşhur bir sanayi şehridir." },
    { plate: "17", name: "Çanakkale", desc: "Çanakkale, tarihi savaşların yaşandığı Gelibolu Yarımadası'na ev sahipliği yapar." },
    { plate: "18", name: "Çankırı", desc: "Çankırı, İç Anadolu'da yer alır ve tuz mağaralarıyla dikkat çeker." },
    { plate: "19", name: "Çorum", desc: "Çorum, leblebisi ve tarihi Hitit kalıntılarıyla bilinir." },
    { plate: "20", name: "Denizli", desc: "Denizli, Pamukkale travertenleri ve horozuyla dünyaca ünlüdür." },
    { plate: "21", name: "Diyarbakır", desc: "Diyarbakır, tarihi surları ve karpuzuyla meşhurdur." },
    { plate: "22", name: "Edirne", desc: "Edirne, Mimar Sinan'ın ustalık eseri Selimiye Camii'ne ev sahipliği yapar." },
    { plate: "23", name: "Elazığ", desc: "Elazığ, Gakkoşlar diyarı olarak bilinir ve Harput Kalesi ile meşhurdur." },
    { plate: "24", name: "Erzincan", desc: "Erzincan, bakırcılık sanatı ve tulum peyniri ile öne çıkar." },
    { plate: "25", name: "Erzurum", desc: "Erzurum, Palandöken Dağı ile kış turizminin önemli merkezlerindendir." },
    { plate: "26", name: "Eskişehir", desc: "Eskişehir, Porsuk Çayı ve öğrenci şehri kimliğiyle dinamik bir ildir." },
    { plate: "27", name: "Gaziantep", desc: "Gaziantep, mutfağıyla UNESCO tarafından tescillenmiş bir gastronomi şehridir." },
    { plate: "28", name: "Giresun", desc: "Giresun, fındığın başkentidir." },
    { plate: "29", name: "Gümüşhane", desc: "Gümüşhane, tarihi yaylaları ve doğal güzellikleri ile bilinir." },
    { plate: "30", name: "Hakkari", desc: "Hakkari, sarp dağları ve eşsiz kış manzaralarıyla dikkat çeker." },
    { plate: "31", name: "Hatay", desc: "Hatay, medeniyetlerin beşiği ve mutfağıyla ünlü güzide bir ilimizdir." },
    { plate: "32", name: "Isparta", desc: "Isparta, gülleri ve halılarıyla Türkiye'nin gül bahçesidir." },
    { plate: "33", name: "Mersin", desc: "Mersin, tantunisi, narenciyesi ve sahil şeridiyle çok önemlidir." },
    { plate: "34", name: "İstanbul", desc: "İstanbul, Türkiye'nin kalbi, iki kıtayı birbirine bağlayan dünya metropolisidir." },
    { plate: "35", name: "İzmir", desc: "İzmir, Ege'nin incisi, kordonu ve tarihi Saat Kulesi ile ünlüdür." },
    { plate: "36", name: "Kars", desc: "Kars, ters laleleri ve tarihi Ani Harabeleri ile meşhurdur." },
    { plate: "37", name: "Kastamonu", desc: "Kastamonu, Karadeniz'in tarihi dokusunu koruyan önemli bir şehridir." },
    { plate: "38", name: "Kayseri", desc: "Kayseri, mantısı, pastırması ve Erciyes Dağı ile tanınır." },
    { plate: "39", name: "Kırklareli", desc: "Kırklareli, ormanları ve sakin yaşamıyla Trakya'nın şirin bir ilidir." },
    { plate: "40", name: "Kırşehir", desc: "Kırşehir, Ahi Evran'ın memleketi ve kültür şehridir." },
    { plate: "41", name: "Kocaeli", desc: "Kocaeli, Türkiye'nin önemli sanayi ve liman kentlerinden biridir." },
    { plate: "42", name: "Konya", desc: "Konya, Mevlana Celaleddin Rumi'nin şehri ve etli ekmeğiyle meşhurdur." },
    { plate: "43", name: "Kütahya", desc: "Kütahya, çinileri ve tarihi konaklarıyla ünlü bir ildir." },
    { plate: "44", name: "Malatya", desc: "Malatya, kayısısı ile tüm dünyada haklı bir üne sahiptir." },
    { plate: "45", name: "Manisa", desc: "Manisa, Mesir Macunu ve Spil Dağı ile bilinir." },
    { plate: "46", name: "Kahramanmaraş", desc: "Kahramanmaraş, dondurması ve kahramanlık destanlarıyla tanınır." },
    { plate: "47", name: "Mardin", desc: "Mardin, taş evleri ve eşsiz tarihi atmosferiyle büyüleyicidir." },
    { plate: "48", name: "Muğla", desc: "Muğla, Bodrum, Marmaris, Fethiye gibi ilçeleriyle turizm cennetidir." },
    { plate: "49", name: "Muş", desc: "Muş, Malazgirt Ovası'na ve tarihi lalesi ile bilinir." },
    { plate: "50", name: "Nevşehir", desc: "Nevşehir, Kapadokya'nın kalbi ve peribacaları diyarıdır." },
    { plate: "51", name: "Niğde", desc: "Niğde, tarımı ve Hacı Bektaş Veli ile anılan kültürel dokusuyla önemlidir." },
    { plate: "52", name: "Ordu", desc: "Ordu, fındık bahçeleri ve yaylalarıyla ünlü bir Karadeniz şehridir." },
    { plate: "53", name: "Rize", desc: "Rize, çayın başkenti ve yeşilin her tonunun bulunduğu bir doğa harikasıdır." },
    { plate: "54", name: "Sakarya", desc: "Sakarya, sanayisi ve doğal güzellikleriyle Marmara'nın önemli bir ilidir." },
    { plate: "55", name: "Samsun", desc: "Samsun, Milli Mücadele'nin başladığı ve Karadeniz'in en büyük şehridir." },
    { plate: "56", name: "Siirt", desc: "Siirt, büryan kebabı ve fıstığıyla tanınır." },
    { plate: "57", name: "Sinop", desc: "Sinop, Türkiye'nin en kuzey ucu ve mutlu insanlar şehri olarak bilinir." },
    { plate: "58", name: "Sivas", desc: "Sivas, tarihi medreseleri, kangal köpeği ve geniş coğrafyasıyla bilinir." },
    { plate: "59", name: "Tekirdağ", desc: "Tekirdağ, köftesi ve Trakya'nın önemli tarım merkezlerinden biri olmasıyla öne çıkar." },
    { plate: "60", name: "Tokat", desc: "Tokat, yaprağı ve tarihi çarşılarıyla meşhurdur." },
    { plate: "61", name: "Trabzon", desc: "Trabzon, Sümela Manastırı ve yaylalarıyla Karadeniz'in çok önemli turizm şehridir." },
    { plate: "62", name: "Tunceli", desc: "Tunceli, Munzur Vadisi ve bakir doğasıyla harika bir ildir." },
    { plate: "63", name: "Şanlıurfa", desc: "Şanlıurfa, Göbeklitepe, Balıklıgöl ve efsanelerle dolu tarihiyle peygamberler şehridir." },
    { plate: "64", name: "Uşak", desc: "Uşak, halısı, battaniyesi ve Karun Hazineleri ile tanınır." },
    { plate: "65", name: "Van", desc: "Van, kaşarı, kahvaltısı ve eşsiz Van Gölü ile özel bir ildir." },
    { plate: "66", name: "Yozgat", desc: "Yozgat, İç Anadolu'nun merkezinde yer alan köklü bir geçmişe sahiptir." },
    { plate: "67", name: "Zonguldak", desc: "Zonguldak, madenleri ve ormanlarıyla Türkiye'nin kömür diyarıdır." },
    { plate: "68", name: "Aksaray", desc: "Aksaray, Kapadokya bölgesinin giriş kapısı ve tarihi kervansaraylarıyla bilinir." },
    { plate: "69", name: "Bayburt", desc: "Bayburt, pestili ve tarihi kaleleriyle meşhurdur." },
    { plate: "70", name: "Karaman", desc: "Karaman, elması, bisküvisi ve Türk dilinin başkenti olmasıyla ünlüdür." },
    { plate: "71", name: "Kırıkkale", desc: "Kırıkkale, silah sanayisi ve Kızılırmak üzerindeki köprüleriyle bilinir." },
    { plate: "72", name: "Batman", desc: "Batman, Hasankeyf antik kenti ile tarihi bir mirasa sahiptir." },
    { plate: "73", name: "Şırnak", desc: "Şırnak, doğal güzellikleri ve yöresel kültürü ile dikkat çeker." },
    { plate: "74", name: "Bartın", desc: "Bartın, filyos nehri, sahil şeridi ve doğal güzellikleriyle meşhurdur." },
    { plate: "75", name: "Ardahan", desc: "Ardahan, kaşar peyniri ve doğal yaylalarıyla öne çıkar." },
    { plate: "76", name: "Iğdır", desc: "Iğdır, doğunun Çukurovası olarak bilinir ve pamuk yetişen ender yerlerdendir." },
    { plate: "77", name: "Yalova", desc: "Yalova, termal kaplıcaları ve çiçekçiliğiyle ünlü Marmara ilidir." },
    { plate: "78", name: "Karabük", desc: "Karabük, Amasra gibi turistik yerlere ve demir çelik sanayisine sahiptir." },
    { plate: "79", name: "Kilis", desc: "Kilis, Türkiye'nin güney sınırında yer alan stratejik ve kültürel bir ildir." },
    { plate: "80", name: "Osmaniye", desc: "Osmaniye, yer fıstığı ve Çukurova'nın bereketli topraklarıyla tanınır." },
    { plate: "81", name: "Düzce", desc: "Düzce, fındığı ve yaylalarıyla Batı Karadeniz'in yeşil şehridir." }
];
