const POSA_CATEGORIES = {
    narenciye: {
        label: 'Narenciye',
        icon: '🍊',
        description: 'Portakal, mandalina ve limon kabuklarından pektin, uçucu yağ ve lif üretimi.',
        compounds: [
            { name: 'Pektin', value: '12–35 $/kg', market: '~1,2 Milyar $' },
            { name: 'Uçucu Yağ', value: '10–40 $/kg', market: '~25 Milyar $' },
            { name: 'Narenciye Lifi', value: '8–25 $/kg', market: '~1,1 Milyar $' },
        ],
    },
    findik: {
        label: 'Fındık',
        icon: '🌰',
        description: 'Fındık kabuğu ve zarından aktif karbon, fenolik ekstreler ve diyet lifi üretimi.',
        compounds: [
            { name: 'Aktif Karbon', value: '1–5 $/kg', market: 'Su & hava arıtma' },
            { name: 'Fenolik Ekstreler', value: '20–100 $/kg', market: '~2 Milyar $' },
            { name: 'Diyet Lifi', value: '3–15 $/kg', market: '~8,5–10 Milyar $' },
        ],
    },
    uzum: {
        label: 'Üzüm',
        icon: '🍇',
        description: 'Üzüm cibresi ve çekirdeğinden proantosiyanidin, antosiyanin ve sabit yağ üretimi.',
        compounds: [
            { name: 'Proantosiyanidin', value: '20–200 $/kg', market: '~276 Milyon $' },
            { name: 'Antosiyanin', value: '15–50 $/kg', market: 'Doğal boya pazarı' },
            { name: 'Üzüm Çekirdeği Yağı', value: '10–30 $/kg', market: '~166 Milyon $' },
        ],
    },
    zeytin: {
        label: 'Zeytin',
        icon: '🫒',
        description: 'Zeytin yaprağı ve pirinasından oleuropein, polifenol ve aktif karbon üretimi.',
        compounds: [
            { name: 'Oleuropein', value: '100–300 $/kg', market: '1–4 Milyar $ potansiyel' },
            { name: 'Polifenol', value: '20–100 $/kg', market: '~2 Milyar $' },
            { name: 'Aktif Karbon', value: '1–5 $/kg', market: 'Endüstriyel filtrasyon' },
        ],
    },
    cay: {
        label: 'Çay',
        icon: '🍵',
        description: 'Çay posası ve saplarından kateşin, L-teanin ve kafein ekstraksiyonu.',
        compounds: [
            { name: 'Kateşin', value: '40–150 $/kg', market: 'Antioksidan takviye' },
            { name: 'L-teanin', value: '50–200 $/kg', market: 'Yükselen takviye yıldızı' },
            { name: 'Kafein', value: '5–15 $/kg', market: 'Enerji içeceği hammaddesi' },
        ],
    },
    tahil: {
        label: 'Tahıl',
        icon: '🌾',
        description: 'Buğday kepeği ve pirinç kabuğundan ferulik asit, arabinoksilanlar ve fitosterol üretimi.',
        compounds: [
            { name: 'Ferulik Asit', value: '150–500 $/kg', market: 'Kozmetik & antioksidan' },
            { name: 'Arabinoksilanlar', value: '20–80 $/kg', market: 'Prebiyotik lif' },
            { name: 'Fitosterol', value: '10–50 $/kg', market: 'Kolesterol düşürücü' },
        ],
    },
    diger: {
        label: 'Özel Ürün',
        icon: '🌿',
        description: 'Bölgeye özgü tarımsal atıklardan çeşitli yüksek katma değerli biyoaktif bileşenler.',
        compounds: [
            { name: 'Biyoaktif Ekstreler', value: '20–500 $/kg', market: 'Takviye gıda & kozmetik' },
            { name: 'Doğal Pigmentler', value: '20–200 $/kg', market: '~2,1 Milyar $' },
            { name: 'Bitkisel Protein', value: '5–25 $/kg', market: '~14–22 Milyar $' },
        ],
    },
};

// potential: 'yüksek' | 'orta' | 'başlangıç'
// extra: PDF'den alınan özel not (isteğe bağlı)
const posaProvinces = [
    { plate: '01', category: 'narenciye', potential: 'yüksek',   extra: 'Antalya-Mersin-Adana hattındaki narenciye fabrikalarından pektin + uçucu yağ + lif üretimi için hazır hammadde.' },
    { plate: '02', category: 'diger',     potential: 'orta',     extra: 'Antep fıstığı kabuklarından fenolik ekstreler; tütün atıklarından bitkisel bileşenler.' },
    { plate: '03', category: 'diger',     potential: 'orta',     extra: 'Haşhaş kapsülünden alkaloid; domates posasından likopen ve pektin.' },
    { plate: '04', category: 'tahil',     potential: 'başlangıç',extra: 'Buğday samanından selüloz ve hemiselüloz; arpa kepeğinden beta-glukan.' },
    { plate: '05', category: 'diger',     potential: 'orta',     extra: 'Elma posasından pektin ve doğal şeker; meyve atıklarından doğal pigment.' },
    { plate: '06', category: 'tahil',     potential: 'yüksek',   extra: 'Konya-Ankara hattı tahıl biyorafinerisi: buğday kepeğinden ferulik asit ve arabinoksilanlar.' },
    { plate: '07', category: 'narenciye', potential: 'yüksek',   extra: 'Türkiye\'nin narenciye başkenti. Fabrika kapısındaki kabuk atıkları pektin + uçucu yağ + lif için hazır hammadde.' },
    { plate: '08', category: 'cay',       potential: 'yüksek',   extra: 'Rize-Trabzon-Artvin çay hattının üçüncü büyük bölgesel fırsatı. Çay sapı ve posasından kateşin + L-teanin.' },
    { plate: '09', category: 'zeytin',    potential: 'yüksek',   extra: 'İncir posasından pektin ve şeker; zeytin yapraklarından oleuropein ve polifenol.' },
    { plate: '10', category: 'zeytin',    potential: 'orta',     extra: 'Zeytinyağı üretim atığı pirinadan polifenol; ayçiçeği tablasından doğal renklendirici.' },
    { plate: '11', category: 'diger',     potential: 'orta',     extra: 'Meyve/sebze atıklarından doğal boyalar ve diyet lifi (Bursa-Bilecik bölgesi PDF\'de özel olarak belirtilmiş).' },
    { plate: '12', category: 'diger',     potential: 'başlangıç',extra: 'Arı ürünleri atıklarından propolis ve balmumu bileşenleri; tıbbi bitkilerden ekstrakt.' },
    { plate: '13', category: 'diger',     potential: 'başlangıç',extra: 'Meyve atıklarından pektin; hayvancılık atıklarından biyogaz ve kolajen.' },
    { plate: '14', category: 'diger',     potential: 'orta',     extra: 'Mantar misel atıklarından beta-glukan; orman yan ürünlerinden lignin ve selüloz.' },
    { plate: '15', category: 'diger',     potential: 'yüksek',   extra: 'Gül yaprak ve petali atıklarından gül yağı ve gül suyu; Isparta gül ekonomisi Türkiye\'nin eşsiz fırsatı.' },
    { plate: '16', category: 'diger',     potential: 'yüksek',   extra: 'Meyve/sebze atıklarından doğal boyalar ve diyet lifi (PDF\'de Bursa/Bilecik özel bölge olarak geçiyor).' },
    { plate: '17', category: 'zeytin',    potential: 'yüksek',   extra: 'Kaz Dağları zeytinliklerinde standart bölgelere kıyasla 50 kata kadar daha yüksek oleuropein konsantrasyonu tespit edilmiş.' },
    { plate: '18', category: 'tahil',     potential: 'başlangıç',extra: 'Şeker pancarı posasından pektin ve biyogaz; buğday samanından selüloz.' },
    { plate: '19', category: 'tahil',     potential: 'orta',     extra: 'Nohut kabuklarından bitkisel protein; buğday samanından ferulik asit.' },
    { plate: '20', category: 'uzum',      potential: 'yüksek',   extra: 'Manisa-Denizli üzüm cibresi işleme ünitesi: antioksidan ekstrakt, antosiyanin ve üzüm çekirdeği yağı.' },
    { plate: '21', category: 'uzum',      potential: 'orta',     extra: 'Üzüm cibresi ve pamuk sapından selüloz; karpuz kabuğundan likopen.' },
    { plate: '22', category: 'tahil',     potential: 'yüksek',   extra: 'Konya-Ankara-Edirne tahıl biyorafinerisi hattı. Çeltik kabuğundan biyoçar ve gama-orizanol (PDF\'de özel proje).' },
    { plate: '23', category: 'uzum',      potential: 'orta',     extra: 'Üzüm cibresi ve kayısı çekirdeğinden sabit yağ; meyve atıklarından doğal pigment.' },
    { plate: '24', category: 'diger',     potential: 'orta',     extra: 'Kiraz ve elma posasından pektin ve doğal antosiyanin pigment; tulum peyniri yan ürünlerinden protein.' },
    { plate: '25', category: 'tahil',     potential: 'başlangıç',extra: 'Arpa ve buğday samanından beta-glukan ve prebiyotik lif; koyun yünü atıklarından keratin.' },
    { plate: '26', category: 'tahil',     potential: 'orta',     extra: 'Buğday ve arpa kepeğinden ferulik asit; şeker pancarı posasından pektin ve biyoetanol.' },
    { plate: '27', category: 'zeytin',    potential: 'yüksek',   extra: 'Gaziantep-Şanlıurfa-Hatay baklagil + zeytin entegre tesisi: baklagilden bitkisel protein konsantresi, zeytin yaprağından oleuropein (PDF\'de özel proje).' },
    { plate: '28', category: 'findik',    potential: 'yüksek',   extra: 'Giresun-Ordu-Trabzon fındık ileri dönüşüm tesisi: fenolik ekstreler, diyet lifi, aktif karbon (PDF\'de özel proje).' },
    { plate: '29', category: 'findik',    potential: 'orta',     extra: 'Fındık kabuğundan aktif karbon ve fenolik ekstreler; bal mumu atıklarından propolis.' },
    { plate: '30', category: 'diger',     potential: 'başlangıç',extra: 'Tıbbi ve aromatik bitkilerden uçucu yağ; dağ balı atıklarından propolis ve balmumu.' },
    { plate: '31', category: 'zeytin',    potential: 'yüksek',   extra: 'Zeytin + narenciye + baklagil entegre: oleuropein, narenciye pektini, bitkisel protein konsantresi.' },
    { plate: '32', category: 'diger',     potential: 'yüksek',   extra: 'Isparta gül ekonomisi: gül petali atıklarından gül yağı (dünyaca aranan parfüm hammaddesi) ve gül suyu.' },
    { plate: '33', category: 'narenciye', potential: 'yüksek',   extra: 'Antalya-Mersin-Adana narenciye biyorafinerisi hattı. Fabrika atık kabukları uçucu yağ + pektin + lif üretimi için hazır.' },
    { plate: '34', category: 'uzum',      potential: 'orta',     extra: 'Bağcılık cibresi ve tarım dışı gıda sektörü atıklarından polifenol ekstraksiyonu.' },
    { plate: '35', category: 'uzum',      potential: 'yüksek',   extra: 'Üzüm + zeytin bölgesi. Üzüm cibresi polifenol ve antosiyanin; zeytin yaprağından oleuropein.' },
    { plate: '36', category: 'diger',     potential: 'başlangıç',extra: 'Süt endüstrisi peynir altı suyundan laktoz ve bitkisel protein; bal ve arıcılık atıklarından propolis.' },
    { plate: '37', category: 'diger',     potential: 'orta',     extra: 'Çeltik işleme artıklarından gama-orizanol ve biyoçar; sarımsak atıklarından alliin ve flavonoidler.' },
    { plate: '38', category: 'tahil',     potential: 'orta',     extra: 'Buğday ve şeker pancarı işleme atıklarından ferulik asit ve pektin; patates atıklarından nişasta türevleri.' },
    { plate: '39', category: 'tahil',     potential: 'orta',     extra: 'Ayçiçeği tablası ve samanından fenolik ekstreler ve biyoetanol; buğday kepeğinden ferulik asit.' },
    { plate: '40', category: 'tahil',     potential: 'orta',     extra: 'Nohut ve buğday atıklarından bitkisel protein ve prebiyotik lif; şeker pancarı posasından pektin.' },
    { plate: '41', category: 'diger',     potential: 'orta',     extra: 'Çilek ve domates atıklarından antosiyanin ve likopen; fındık artıklarından fenolik ekstreler.' },
    { plate: '42', category: 'tahil',     potential: 'yüksek',   extra: 'Konya-Ankara hattı tahıl biyorafinerisi: buğday kepeğinden ferulik asit + arabinoksilanlar + fitosterol (PDF\'de özel proje).' },
    { plate: '43', category: 'diger',     potential: 'orta',     extra: 'Şeker pancarı posasından pektin ve biyoetanol; elma atıklarından pektin ve doğal şeker.' },
    { plate: '44', category: 'diger',     potential: 'yüksek',   extra: 'Malatya kayısı çekirdeği yağı: oleik asit ve linoleik asit bakımından zengin, kozmetik ve takviye gıda sektörünün aranan hammaddesi.' },
    { plate: '45', category: 'uzum',      potential: 'yüksek',   extra: 'Manisa-Denizli üzüm cibresi işleme ünitesi: antioksidan ekstrakt, antosiyanin, üzüm çekirdeği yağı (PDF\'de özel proje).' },
    { plate: '46', category: 'diger',     potential: 'orta',     extra: 'Kırmızı biber sapı ve tohumundan kapsaisin; susam küspesinden bitkisel protein ve lignin.' },
    { plate: '47', category: 'diger',     potential: 'orta',     extra: 'Mercimek ve buğday atıklarından bitkisel protein konsantresi; zeytin atıklarından polifenol.' },
    { plate: '48', category: 'zeytin',    potential: 'yüksek',   extra: 'Zeytin + mandalina bölgesi. Zeytinden oleuropein; narenciye kabuğundan uçucu yağ ve pektin.' },
    { plate: '49', category: 'tahil',     potential: 'başlangıç',extra: 'Şeker pancarı posasından pektin ve biyogaz; arpa samanından selüloz.' },
    { plate: '50', category: 'uzum',      potential: 'orta',     extra: 'Üzüm cibresi antosiyanin ve proantosiyanidin; patates atıklarından nişasta türevleri.' },
    { plate: '51', category: 'diger',     potential: 'orta',     extra: 'Patates atıklarından nişasta türevleri ve biyoplastik hammaddesi; elma posasından pektin.' },
    { plate: '52', category: 'findik',    potential: 'yüksek',   extra: 'Giresun-Ordu-Trabzon fındık ileri dönüşüm tesisi: kabuktan aktif karbon, zardan fenolik ekstreler (PDF\'de özel proje).' },
    { plate: '53', category: 'cay',       potential: 'yüksek',   extra: 'Rize çay posa ekonomisinin merkezi. Çay sapı ve düşük kaliteli yapraklardan kateşin + L-teanin + kafein üretimi.' },
    { plate: '54', category: 'findik',    potential: 'orta',     extra: 'Fındık kabuğundan aktif karbon ve fenolik ekstreler; çilek atıklarından antosiyanin.' },
    { plate: '55', category: 'findik',    potential: 'orta',     extra: 'Fındık artıkları ve tütün saplarından fenolik bileşenler; çeltik kepeğinden gama-orizanol.' },
    { plate: '56', category: 'diger',     potential: 'orta',     extra: 'Siirt fıstığı kabuğundan fenolik ekstreler; pirinç artıklarından gama-orizanol.' },
    { plate: '57', category: 'findik',    potential: 'orta',     extra: 'Fındık ve elma atıklarından fenolik ekstreler ve pektin; orman yan ürünlerinden lignin.' },
    { plate: '58', category: 'tahil',     potential: 'orta',     extra: 'Şeker pancarı posasından pektin ve biyoetanol; elma ve buğday atıklarından ferulik asit.' },
    { plate: '59', category: 'uzum',      potential: 'yüksek',   extra: 'Manisa-Denizli-Tekirdağ üzüm cibresi işleme ünitesi: antioksidan ekstrakt ve antosiyanin pigment (PDF\'de özel proje).' },
    { plate: '60', category: 'uzum',      potential: 'orta',     extra: 'Üzüm cibresi antosiyanin; nohut ve domates atıklarından bitkisel protein ve likopen.' },
    { plate: '61', category: 'findik',    potential: 'yüksek',   extra: 'Giresun-Ordu-Trabzon fındık ileri dönüşüm tesisi. Ayrıca çay hattı üzerinde: kateşin + fenolik ekstreler.' },
    { plate: '62', category: 'diger',     potential: 'başlangıç',extra: 'Munzur vadisi tıbbi bitkilerinden uçucu yağ ve ekstrakt; bal atıklarından propolis.' },
    { plate: '63', category: 'diger',     potential: 'yüksek',   extra: 'Gaziantep-Şanlıurfa-Hatay baklagil + zeytin entegre tesisi: bitkisel protein konsantresi ve oleuropein (PDF\'de özel proje).' },
    { plate: '64', category: 'uzum',      potential: 'orta',     extra: 'Üzüm cibresi ve şeker pancarı atıklarından antosiyanin ve pektin.' },
    { plate: '65', category: 'diger',     potential: 'başlangıç',extra: 'Dağ balı atıklarından propolis; tıbbi ve aromatik bitkilerden uçucu yağ.' },
    { plate: '66', category: 'tahil',     potential: 'orta',     extra: 'Şeker pancarı posasından pektin; nohut atıklarından bitkisel protein; elma posasından doğal şeker.' },
    { plate: '67', category: 'findik',    potential: 'orta',     extra: 'Fındık kabuğundan aktif karbon ve fenolik ekstreler; maden atıklarıyla kombine çevre teknolojisi.' },
    { plate: '68', category: 'tahil',     potential: 'başlangıç',extra: 'Buğday ve şeker pancarı işleme atıklarından ferulik asit ve biyoetanol.' },
    { plate: '69', category: 'diger',     potential: 'başlangıç',extra: 'Bayburt taşı gibi mineral kaynakları; bal ve tıbbi bitkilerden uçucu yağ üretimi.' },
    { plate: '70', category: 'diger',     potential: 'orta',     extra: 'Elma posasından pektin ve doğal şeker; kiraz atıklarından antosiyanin pigment.' },
    { plate: '71', category: 'tahil',     potential: 'başlangıç',extra: 'Buğday samanından selüloz ve ferulik asit; silah sanayii yakınlığı teknik kimyasal üretim avantajı.' },
    { plate: '72', category: 'diger',     potential: 'başlangıç',extra: 'Pamuk sapı ve lifinden selüloz ve biyokompozit; Hasankeyf bölgesi arıcılık atıkları.' },
    { plate: '73', category: 'uzum',      potential: 'başlangıç',extra: 'Üzüm cibresi antosiyanin; buğday atıklarından selüloz.' },
    { plate: '74', category: 'findik',    potential: 'orta',     extra: 'Fındık ve mısır atıklarından fenolik ekstreler ve lignin; orman ürünleri yan ürünleri.' },
    { plate: '75', category: 'diger',     potential: 'başlangıç',extra: 'Kaz keseği ve tüy atıklarından keratin; bal ve arıcılık atıklarından propolis.' },
    { plate: '76', category: 'diger',     potential: 'başlangıç',extra: 'Pamuk ve kayısı atıklarından selüloz ve çekirdeği yağı; Iğdır doğu kapısı konumu.' },
    { plate: '77', category: 'diger',     potential: 'orta',     extra: 'Çiçek atıklarından uçucu yağ ve doğal boya; domates ve salatalık atıklarından likopen ve pektin.' },
    { plate: '78', category: 'findik',    potential: 'orta',     extra: 'Fındık artıklarından aktif karbon; Karabük demir-çelik sektörüyle biyokompozit entegrasyonu fırsatı.' },
    { plate: '79', category: 'zeytin',    potential: 'yüksek',   extra: 'Kilis zeytin atıklarından oleuropein ve polifenol (PDF\'de özel proje). Küçük ölçekli bir tesisin ekonomiyi dönüştürme potansiyeli yüksek.' },
    { plate: '80', category: 'diger',     potential: 'yüksek',   extra: 'Yer fıstığı küspesinden bitkisel protein konsantresi; pamuk sapından selüloz ve biyokompozit.' },
    { plate: '81', category: 'findik',    potential: 'orta',     extra: 'Fındık kabuğundan aktif karbon ve fenolik ekstreler; orman yan ürünlerinden lignin.' },
];
